# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41a5ef6e0c068a5930ec6c0ebbef26de153711946c2c3336724bb39e6e4bb5908c5160889786c06d319b9b1120ca0179027f368baa2825ee47ab4145d676905e

test:
  secret_key_base: 7e1800a8fe7ce517427da22e03ed52e970f14ce7f25f7ffc5604fc6c623884556d7b1672cfb129c4ac3ee2b6979a3bf0ff007e6a58e51de2f1491b5ec63316ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
